name: PR lint

on:
  pull_request:
    types: [opened, edited, reopened]

permissions:
  contents: read

jobs:
  prlint:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: gavinastur/pr-linter-action@66de6937c3647f7cffd18aadd255ce804e9f764f # v1.2.1
